# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b685edcefe6f74b42cc3995570a5206ab56bf486b5520fa2349bba084cf7a4f877dac6d38fbf36965079cc647396bdd4997d8e349945f080b77f8620fedbcec

test:
  secret_key_base: 5d4ab1dd1b0312d33c15dedd15578858241d16545f22c502181504c5e042738ebc1984a76cec8fc61f55c43790d33f2a9c9dbdb549d7d07e17247b9e0d0e45f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
